# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MewAgentPointRecord',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('points', models.IntegerField(default=0)),
                ('related_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Record',
                'verbose_name_plural': 'Agent Records',
            },
        ),
        migrations.CreateModel(
            name='MewCertificate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('private_key', models.TextField(default='', verbose_name='Private Key')),
                ('public_key', models.TextField(default='', verbose_name='Public Key')),
                ('checksum_salt', models.TextField(default='', verbose_name='Checksum Salt')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='MewCode',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('code_value', models.CharField(default='', max_length=16, unique=True, verbose_name='Code Value')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
            },
        ),
        migrations.CreateModel(
            name='MewCodeBucket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(default='Untitled Bucket', max_length=64, unique=True, verbose_name='Name')),
                ('code_count', models.IntegerField(default=100, help_text='Current rate: 100 points = 1 code', verbose_name='Code Count')),
                ('code_export', models.TextField(blank=True, verbose_name='Code Export')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Bucket',
                'verbose_name_plural': 'Code Buckets',
            },
        ),
        migrations.CreateModel(
            name='MewDevice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('unique_id', models.CharField(default='', max_length=40, unique=True, verbose_name='Unique ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='MewVersion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('version_string', models.CharField(default='', max_length=16, verbose_name='Version String')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
        migrations.AddField(
            model_name='mewcode',
            name='bind_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MewApi.MewDevice'),
        ),
        migrations.AddField(
            model_name='mewcode',
            name='bucket',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='MewApi.MewCodeBucket'),
        ),
        migrations.AddField(
            model_name='mewcode',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
