# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewcode',
            name='bind_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MewApi.MewDevice'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
    ]
