# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mewagentpointrecord',
            options={'verbose_name': '\u4ee3\u7406\u70b9\u6570', 'verbose_name_plural': '\u4ee3\u7406\u70b9\u6570'},
        ),
        migrations.AlterModelOptions(
            name='mewcertificate',
            options={'verbose_name': '\u8bc1\u4e66', 'verbose_name_plural': '\u8bc1\u4e66'},
        ),
        migrations.AlterModelOptions(
            name='mewcode',
            options={'verbose_name': '\u6388\u6743', 'verbose_name_plural': '\u6388\u6743'},
        ),
        migrations.AlterModelOptions(
            name='mewcodebucket',
            options={'verbose_name': '\u6388\u6743\u6c60', 'verbose_name_plural': '\u6388\u6743\u6c60'},
        ),
        migrations.AlterModelOptions(
            name='mewdevice',
            options={'verbose_name': '\u8bbe\u5907', 'verbose_name_plural': '\u8bbe\u5907'},
        ),
        migrations.AlterModelOptions(
            name='mewversion',
            options={'verbose_name': '\u7248\u672c', 'verbose_name_plural': '\u7248\u672c'},
        ),
        migrations.AlterField(
            model_name='mewagentpointrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewagentpointrecord',
            name='points',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u6570'),
        ),
        migrations.AlterField(
            model_name='mewagentpointrecord',
            name='related_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AlterField(
            model_name='mewcertificate',
            name='checksum_salt',
            field=models.TextField(default='', verbose_name='\u76d0'),
        ),
        migrations.AlterField(
            model_name='mewcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewcertificate',
            name='private_key',
            field=models.TextField(default='', verbose_name='\u79c1\u94a5'),
        ),
        migrations.AlterField(
            model_name='mewcertificate',
            name='public_key',
            field=models.TextField(default='', verbose_name='\u516c\u94a5'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='bind_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MewApi.MewDevice', verbose_name='\u5173\u8054\u8bbe\u5907'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='bucket',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='MewApi.MewCodeBucket', verbose_name='\u6388\u6743\u6c60'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='code_value',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='\u6388\u6743\u7801'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4f7f\u7528\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='code_count',
            field=models.IntegerField(default=100, help_text='\u5f53\u524d\u5151\u6362\u6bd4\u7387: 100 \u70b9\u6570 = 1 \u6388\u6743', verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='code_export',
            field=models.TextField(blank=True, verbose_name='\u5bfc\u51fa'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='name',
            field=models.CharField(default='\u672a\u547d\u540d\u6388\u6743\u6c60', max_length=64, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AlterField(
            model_name='mewdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewdevice',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='mewdevice',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u6709\u8005'),
        ),
        migrations.AlterField(
            model_name='mewdevice',
            name='unique_id',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='\u8bbe\u5907\u53f7'),
        ),
        migrations.AlterField(
            model_name='mewversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='mewversion',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='mewversion',
            name='version_string',
            field=models.CharField(default='', max_length=16, verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
