# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0002_auto_20170521_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='MewCodeBucket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('code_count', models.IntegerField(default=0, verbose_name='Code Count')),
                ('code_export', models.TextField(editable=False, verbose_name='Code Export')),
            ],
            options={
                'verbose_name': 'Code Bucket',
                'verbose_name_plural': 'Code Buckets',
            },
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='used_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Used At'),
        ),
    ]
