# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0003_auto_20170521_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MewCertificate',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('private_key', models.TextField(verbose_name='Private Key')),
                ('public_key', models.TextField(verbose_name='Public Key')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.RemoveField(
            model_name='mewcodebucket',
            name='code_export',
        ),
        migrations.AddField(
            model_name='mewcodebucket',
            name='code_export',
            field=models.ManyToManyField(editable=False, to='MewApi.MewCode', verbose_name='Code Export'),
        ),
    ]
