# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0004_auto_20170521_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mewcodebucket',
            name='name',
            field=models.CharField(default='Untitled Bucket', max_length=64, verbose_name='Name'),
        ),
    ]
