# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0005_mewcodebucket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewcodebucket',
            name='code_count',
            field=models.IntegerField(default=100, verbose_name='Code Count'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='code_export',
            field=models.ManyToManyField(blank=True, to='MewApi.MewCode', verbose_name='Code Export'),
        ),
    ]
