# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0007_auto_20170521_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='mewcode',
            name='bucket',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='MewApi.MewCodeBucket'),
        ),
        migrations.AlterField(
            model_name='mewcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
    ]
