# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MewApi', '0008_auto_20170521_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewcode',
            name='code_value',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='Code Value'),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='name',
            field=models.CharField(default='Untitled Bucket', max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mewdevice',
            name='unique_id',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='Unique ID'),
        ),
    ]
