# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MewApi', '0010_auto_20170522_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='MewAgentPointRecord',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('points', models.IntegerField(default=0)),
                ('related_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Record',
                'verbose_name_plural': 'Agent Records',
            },
        ),
        migrations.AddField(
            model_name='mewcode',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mewcodebucket',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mewdevice',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mewcodebucket',
            name='code_count',
            field=models.IntegerField(default=100, help_text='Current rate: 100 points = 1 code', verbose_name='Code Count'),
        ),
    ]
